# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csmajs/byu064/final-project-buong001-alau030-byu064-imcke003

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csmajs/byu064/final-project-buong001-alau030-byu064-imcke003

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/byu064/final-project-buong001-alau030-byu064-imcke003/CMakeFiles /home/csmajs/byu064/final-project-buong001-alau030-byu064-imcke003//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/byu064/final-project-buong001-alau030-byu064-imcke003/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named runGame

# Build rule for target.
runGame: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 runGame
.PHONY : runGame

# fast build rule for target.
runGame/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/build
.PHONY : runGame/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/main.cpp.s
.PHONY : main.cpp.s

src/Output.o: src/Output.cpp.o
.PHONY : src/Output.o

# target to build an object file
src/Output.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/src/Output.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Output.cpp.o
.PHONY : src/Output.cpp.o

src/Output.i: src/Output.cpp.i
.PHONY : src/Output.i

# target to preprocess a source file
src/Output.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/src/Output.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Output.cpp.i
.PHONY : src/Output.cpp.i

src/Output.s: src/Output.cpp.s
.PHONY : src/Output.s

# target to generate assembly for a file
src/Output.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/src/Output.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Output.cpp.s
.PHONY : src/Output.cpp.s

src/Player.o: src/Player.cpp.o
.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/src/Player.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i
.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/src/Player.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s
.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/src/Player.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/Type_A.o: src/Type_A.cpp.o
.PHONY : src/Type_A.o

# target to build an object file
src/Type_A.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/src/Type_A.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Type_A.cpp.o
.PHONY : src/Type_A.cpp.o

src/Type_A.i: src/Type_A.cpp.i
.PHONY : src/Type_A.i

# target to preprocess a source file
src/Type_A.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/src/Type_A.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Type_A.cpp.i
.PHONY : src/Type_A.cpp.i

src/Type_A.s: src/Type_A.cpp.s
.PHONY : src/Type_A.s

# target to generate assembly for a file
src/Type_A.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/src/Type_A.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Type_A.cpp.s
.PHONY : src/Type_A.cpp.s

src/Type_B.o: src/Type_B.cpp.o
.PHONY : src/Type_B.o

# target to build an object file
src/Type_B.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/src/Type_B.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Type_B.cpp.o
.PHONY : src/Type_B.cpp.o

src/Type_B.i: src/Type_B.cpp.i
.PHONY : src/Type_B.i

# target to preprocess a source file
src/Type_B.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/src/Type_B.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Type_B.cpp.i
.PHONY : src/Type_B.cpp.i

src/Type_B.s: src/Type_B.cpp.s
.PHONY : src/Type_B.s

# target to generate assembly for a file
src/Type_B.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/src/Type_B.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Type_B.cpp.s
.PHONY : src/Type_B.cpp.s

src/Type_C.o: src/Type_C.cpp.o
.PHONY : src/Type_C.o

# target to build an object file
src/Type_C.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/src/Type_C.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Type_C.cpp.o
.PHONY : src/Type_C.cpp.o

src/Type_C.i: src/Type_C.cpp.i
.PHONY : src/Type_C.i

# target to preprocess a source file
src/Type_C.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/src/Type_C.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Type_C.cpp.i
.PHONY : src/Type_C.cpp.i

src/Type_C.s: src/Type_C.cpp.s
.PHONY : src/Type_C.s

# target to generate assembly for a file
src/Type_C.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/src/Type_C.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Type_C.cpp.s
.PHONY : src/Type_C.cpp.s

src/room.o: src/room.cpp.o
.PHONY : src/room.o

# target to build an object file
src/room.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/src/room.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/room.cpp.o
.PHONY : src/room.cpp.o

src/room.i: src/room.cpp.i
.PHONY : src/room.i

# target to preprocess a source file
src/room.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/src/room.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/room.cpp.i
.PHONY : src/room.cpp.i

src/room.s: src/room.cpp.s
.PHONY : src/room.s

# target to generate assembly for a file
src/room.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/src/room.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/room.cpp.s
.PHONY : src/room.cpp.s

src/wrongInput.o: src/wrongInput.cpp.o
.PHONY : src/wrongInput.o

# target to build an object file
src/wrongInput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/src/wrongInput.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/wrongInput.cpp.o
.PHONY : src/wrongInput.cpp.o

src/wrongInput.i: src/wrongInput.cpp.i
.PHONY : src/wrongInput.i

# target to preprocess a source file
src/wrongInput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/src/wrongInput.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/wrongInput.cpp.i
.PHONY : src/wrongInput.cpp.i

src/wrongInput.s: src/wrongInput.cpp.s
.PHONY : src/wrongInput.s

# target to generate assembly for a file
src/wrongInput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/src/wrongInput.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/wrongInput.cpp.s
.PHONY : src/wrongInput.cpp.s

tests/outputTests.o: tests/outputTests.cpp.o
.PHONY : tests/outputTests.o

# target to build an object file
tests/outputTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/outputTests.cpp.o
.PHONY : tests/outputTests.cpp.o

tests/outputTests.i: tests/outputTests.cpp.i
.PHONY : tests/outputTests.i

# target to preprocess a source file
tests/outputTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/outputTests.cpp.i
.PHONY : tests/outputTests.cpp.i

tests/outputTests.s: tests/outputTests.cpp.s
.PHONY : tests/outputTests.s

# target to generate assembly for a file
tests/outputTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/outputTests.cpp.s
.PHONY : tests/outputTests.cpp.s

tests/playerTests.o: tests/playerTests.cpp.o
.PHONY : tests/playerTests.o

# target to build an object file
tests/playerTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/playerTests.cpp.o
.PHONY : tests/playerTests.cpp.o

tests/playerTests.i: tests/playerTests.cpp.i
.PHONY : tests/playerTests.i

# target to preprocess a source file
tests/playerTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/playerTests.cpp.i
.PHONY : tests/playerTests.cpp.i

tests/playerTests.s: tests/playerTests.cpp.s
.PHONY : tests/playerTests.s

# target to generate assembly for a file
tests/playerTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/playerTests.cpp.s
.PHONY : tests/playerTests.cpp.s

tests/roomTests.o: tests/roomTests.cpp.o
.PHONY : tests/roomTests.o

# target to build an object file
tests/roomTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/roomTests.cpp.o
.PHONY : tests/roomTests.cpp.o

tests/roomTests.i: tests/roomTests.cpp.i
.PHONY : tests/roomTests.i

# target to preprocess a source file
tests/roomTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/roomTests.cpp.i
.PHONY : tests/roomTests.cpp.i

tests/roomTests.s: tests/roomTests.cpp.s
.PHONY : tests/roomTests.s

# target to generate assembly for a file
tests/roomTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/roomTests.cpp.s
.PHONY : tests/roomTests.cpp.s

tests/typeATests.o: tests/typeATests.cpp.o
.PHONY : tests/typeATests.o

# target to build an object file
tests/typeATests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/typeATests.cpp.o
.PHONY : tests/typeATests.cpp.o

tests/typeATests.i: tests/typeATests.cpp.i
.PHONY : tests/typeATests.i

# target to preprocess a source file
tests/typeATests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/typeATests.cpp.i
.PHONY : tests/typeATests.cpp.i

tests/typeATests.s: tests/typeATests.cpp.s
.PHONY : tests/typeATests.s

# target to generate assembly for a file
tests/typeATests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/typeATests.cpp.s
.PHONY : tests/typeATests.cpp.s

tests/typeBTests.o: tests/typeBTests.cpp.o
.PHONY : tests/typeBTests.o

# target to build an object file
tests/typeBTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/typeBTests.cpp.o
.PHONY : tests/typeBTests.cpp.o

tests/typeBTests.i: tests/typeBTests.cpp.i
.PHONY : tests/typeBTests.i

# target to preprocess a source file
tests/typeBTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/typeBTests.cpp.i
.PHONY : tests/typeBTests.cpp.i

tests/typeBTests.s: tests/typeBTests.cpp.s
.PHONY : tests/typeBTests.s

# target to generate assembly for a file
tests/typeBTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/typeBTests.cpp.s
.PHONY : tests/typeBTests.cpp.s

tests/typeCTests.o: tests/typeCTests.cpp.o
.PHONY : tests/typeCTests.o

# target to build an object file
tests/typeCTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/typeCTests.cpp.o
.PHONY : tests/typeCTests.cpp.o

tests/typeCTests.i: tests/typeCTests.cpp.i
.PHONY : tests/typeCTests.i

# target to preprocess a source file
tests/typeCTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/typeCTests.cpp.i
.PHONY : tests/typeCTests.cpp.i

tests/typeCTests.s: tests/typeCTests.cpp.s
.PHONY : tests/typeCTests.s

# target to generate assembly for a file
tests/typeCTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/typeCTests.cpp.s
.PHONY : tests/typeCTests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... runGame"
	@echo "... test"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Output.o"
	@echo "... src/Output.i"
	@echo "... src/Output.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/Type_A.o"
	@echo "... src/Type_A.i"
	@echo "... src/Type_A.s"
	@echo "... src/Type_B.o"
	@echo "... src/Type_B.i"
	@echo "... src/Type_B.s"
	@echo "... src/Type_C.o"
	@echo "... src/Type_C.i"
	@echo "... src/Type_C.s"
	@echo "... src/room.o"
	@echo "... src/room.i"
	@echo "... src/room.s"
	@echo "... src/wrongInput.o"
	@echo "... src/wrongInput.i"
	@echo "... src/wrongInput.s"
	@echo "... tests/outputTests.o"
	@echo "... tests/outputTests.i"
	@echo "... tests/outputTests.s"
	@echo "... tests/playerTests.o"
	@echo "... tests/playerTests.i"
	@echo "... tests/playerTests.s"
	@echo "... tests/roomTests.o"
	@echo "... tests/roomTests.i"
	@echo "... tests/roomTests.s"
	@echo "... tests/typeATests.o"
	@echo "... tests/typeATests.i"
	@echo "... tests/typeATests.s"
	@echo "... tests/typeBTests.o"
	@echo "... tests/typeBTests.i"
	@echo "... tests/typeBTests.s"
	@echo "... tests/typeCTests.o"
	@echo "... tests/typeCTests.i"
	@echo "... tests/typeCTests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

